export const EnquiryFormData= [
    {
      header: 'Online Order Enquiry',
      headerUS:'Online Order Enquiry',
      name: 'Orders',
      nameUs: 'Orders',
      selected: true,
      route: '/store/browse/feedback/feedback',
      queryParams: 'orderfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: false,
        hotelEmenity: false,
        GiftSection: false,
        faxNumberSection: false,
        webSiteSection: false,
        Hotel_Name: false,
        orderPara: true,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Order Returns',
      headerUS:'Order Returns',
      name: 'Order Returns',
      nameUs: 'Order Returns',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'orderreturnsfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: false,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
        orderPara: true,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Compliments',
      headerUS:'Compliments',
      name: 'Compliments',
      nameUs: 'Compliments',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'complimentsfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: false,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
        orderPara: false,
        complimentsPara: true,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Complaints',
      headerUS:'Complaints',
      nameUs: 'Complaints',
      name: 'Complaints',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'complaintsfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: false,
        complimentsPara: false,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
        orderPara: false,
        complaintsPara: true,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Product Enquiry',
      headerUS:'Product Enquiry',
      name: 'Product Enquiry',
      nameUs: 'Product Enquiry',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'productenquiryfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: false,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: true,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Product Feedback',
      headerUS:'Product Feedback',
      name: 'Product Feedback',
      nameUs: 'Product Feedback',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'productfeedback',
      enableElements: {
        orderNumber: false,
        addressFields: false,
        addressValidation: false,
        bussinesType: false,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: true,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Stockist Enquiry/Feedback',
      headerUS:'Stockist Enquiry/Feedback',
      name: 'Stockist Enquiry',
      nameUs: 'Stockist Enquiry',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'stockistenquiryfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: false,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
  
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: true,
        hotelAmenities: false,
        spaHotelPara: false
      }
    },
    {
      header: 'Hotel Amenities - UK, Europe, Middle East & Africa',
      headerUS:'Hotel Amenities-USA, Canada and Caribbean',
      name: 'Hotel Amenities',
      nameUs: 'Hotel Amenities EMEA',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'hotelservicesfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: true,
        GiftSection: false,
        webSiteSection: true,
        Hotel_Name: true,
  
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: true,
        spaHotelPara: false
      }
    },
    {
      header: 'Distribution Enquiry - Europe, Middle East & Africa',
      headerUS:'Distribution Inquiry-Europe, Middle East & Africa',
      name: 'Distribution Enquiry - EMEA',
      nameUs: 'Distribution Enquiry - EMEA',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'distributionenquiryemeafeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: false,
        Hotel_Name: false,
  
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: true,
        spaHotelPara: false
      }
    },
    {
      header: 'Distribution Enquiry - UK & Ireland',
      headerUS:'Distribution Enquiry - USA, Canada and Caribbean',
      name: 'Distribution Enquiry - UK & Ireland',
      nameUs: 'Distribution Enquiry - USA, Canada and Caribbean',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'distributionenquiryukirelandfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: true,
        Hotel_Name: false,
  
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: true,
        spaHotelPara: false
      }
    },
    {
      header: 'Agency Enquiry',
      headerUS:'Agency Enquiry',
      name: 'Agency Enquiry',
      nameUs: 'Agency Enquiry',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'agencyenquiryfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: true,
        Hotel_Name: false,
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: true,
        spaHotelPara: false
      }
    },
    {
      header: 'Partnership Enquiry',
      headerUS:'Partnership Enquiry',
      name: 'Partnership Enquiry',
      nameUs: 'Partnership Enquiry',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'partnershipenquiryfeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: true,
        Hotel_Name: true,
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: true,
        spaHotelPara: false
      }
    },
    {
      header: 'Corporate Gifting - UK, Europe, Middle East & Africa',
      headerUS:'Corporate Gifting - UK, Europe, Middle East & Africa',
      name: 'Corporate Gifting - EMEA',
      nameUs: 'Corporate Gifting - EMEA',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'corporategiftemeafeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: false,
        GiftSection: true,
        webSiteSection: true,
        Hotel_Name: true,
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: true,
        spaHotelPara: false
      }
    },
    {
      header: '',
      name: 'Spa hotel',
      nameUs: 'Spa hotel',
      headerUS:'Spa hotel',
      selected: false,
      route: '/store/browse/feedback/feedback',
      queryParams: 'enquiryemeafeedback',
      enableElements: {
        orderNumber: true,
        addressFields: true,
        addressValidation: false,
        bussinesType: true,
        hotelEmenity: false,
        GiftSection: false,
        webSiteSection: true,
        Hotel_Name: true,
        orderPara: false,
        complimentsPara: false,
        complaintsPara: false,
        productEnPara: false,
        productFeedbackPara: false,
        stockistPara: false,
        hotelAmenities: false,
        spaHotelPara: true
      }
    }
  ];